from enum import Enum


class ErrorCode(str, Enum):
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR"
    MISSING_AUTH_HEADER = "MISSING_AUTH_HEADER"
    MISSING_REFRESH_TOKEN = "MISSING_REFRESH_TOKEN"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    TOKEN_BLACKLISTED = "TOKEN_BLACKLISTED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    PASSWORD_VALIDATION_FAILED = "PASSWORD_VALIDATION_FAILED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"

    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    DATASET_NOT_FOUND = "DATASET_NOT_FOUND"
    DATASET_CONFLICT = "DATASET_CONFLICT"
    SEARCH_LOG_NOT_FOUND = "SEARCH_LOG_NOT_FOUND"

    INVALID_SEARCH_QUERY = "INVALID_SEARCH_QUERY"
    VALIDATION_ERROR = "VALIDATION_ERROR"

    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
    TASK_QUEUE_ERROR = "TASK_QUEUE_ERROR"
    ENRICHMENT_SOURCE_ERROR = "ENRICHMENT_SOURCE_ERROR"
    ENRICHMENT_RATE_LIMITED = "ENRICHMENT_RATE_LIMITED"
    ENRICHMENT_PROCESSING_ERROR = "ENRICHMENT_PROCESSING_ERROR"
    EMBEDDING_MODEL_LOAD_FAILED = "EMBEDDING_MODEL_LOAD_FAILED"
    EMBEDDING_ENCODING_FAILED = "EMBEDDING_ENCODING_FAILED"
    EMBEDDING_PERSISTENCE_FAILED = "EMBEDDING_PERSISTENCE_FAILED"
    INTERNAL_ERROR = "INTERNAL_ERROR"
